name: Deploy to LAMP Server

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        rsync -avz --delete ./ sdevsoc@lamp.ms.wits.ac.za:/public_html/
        # Use rsync to transfer your project files. Adjust paths as necessary.
